package ua.tqs.pollution_tqs;


// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@ExtendWith(SeleniumJupiter.class)
class SearchesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  void tearDown() {
    driver.quit();
  }
  @Test
  void searches() {
    String title;
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(831, 699));
    driver.findElement(By.id("cityName")).click();
    driver.findElement(By.id("cityName")).sendKeys("beja");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.id("countryName")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    title = driver.findElement(By.id("result-description")).getText();
    title.contains("Béja, TN");
    driver.findElement(By.id("countryName")).sendKeys("pt");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    title = driver.findElement(By.id("result-description")).getText();
    title.contains("Beja, PT");
    driver.findElement(By.id("cityName")).click();
    driver.findElement(By.id("cityName")).sendKeys("aaaaa");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    title = driver.findElement(By.id("result-error")).getText();
    assertThat(title).isEqualTo("Something went wrong");
  }
}
